import { BuildingBlueprint } from '../classes/BuildingBlueprint';

export enum BuildingCategory {
  FOOD = 'Food and Farming',
  FUN = 'Entertainment',
  HEALTH = 'Health and Sanitation',
  INDUSTRY = 'Industrial Buildings',
  RELIGION = 'Religion',
  GOVT = 'Municipal Buildings',
  STORAGE = 'Storage and Distribution',
  EDUCATION = 'Education',
  MILITARY = 'Military Structures',
}

export const BUILDING_BLUEPRINTS: Record<string, BuildingBlueprint> = {
  ACADEMY: {
    name: 'Academy',
    height: 4,
    width: 4,
    cost: [200, 800, 1000, 1200, 1500],
    employeesRequired: 20,
    desireBox: { baseDesirability: -3, stepDist: 1, stepVal: 1, maxRange: 3 },
    category: BuildingCategory.MILITARY,
  },
  APOTHECARY: {
    name: 'Apothecary',
    height: 1,
    width: 1,
    cost: [6, 24, 30, 36, 45],
    employeesRequired: 5,
    desireBox: { baseDesirability: 1, stepDist: 1, stepVal: -1, maxRange: 1 },
    category: BuildingCategory.HEALTH,
  },
  ARCHITECT: {
    name: 'Architect',
    height: 1,
    width: 1,
    cost: [6, 24, 30, 36, 45],
    employeesRequired: 5,
    // No desirability effect!
    category: BuildingCategory.GOVT,
  },
  BAZAAR: {
    name: 'Bazaar',
    height: 2,
    width: 2,
    cost: [8, 32, 40, 48, 60],
    employeesRequired: 5,
    desireBox: { baseDesirability: -2, stepDist: 1, stepVal: 1, maxRange: 6 },
    category: BuildingCategory.STORAGE,
  },
  BREWERY: {
    name: 'Brewery',
    height: 2,
    width: 2,
    cost: [15, 60, 75, 90, 112],
    employeesRequired: 12,
    desireBox: { baseDesirability: -5, stepDist: 1, stepVal: 1, maxRange: 5 },
    category: BuildingCategory.INDUSTRY,
  },
  BRICKWORKS: {
    name: 'Brickworks',
    height: 2,
    width: 2,
    cost: [12, 48, 60, 72, 90],
    employeesRequired: 12,
    desireBox: { baseDesirability: -4, stepDist: 1, stepVal: 1, maxRange: 4 },
    category: BuildingCategory.INDUSTRY,
  },
  CATTLERANCH: {
    name: 'Cattle Ranch',
    height: 3,
    width: 3,
    cost: [15, 60, 75, 90, 112],
    employeesRequired: 12,
    desireBox: { baseDesirability: -4, stepDist: 1, stepVal: 1, maxRange: 4 },
    category: BuildingCategory.FOOD,
  },
  CHARIOTMAKER: {
    name: 'Chariot Maker',
    height: 4,
    width: 4,
    cost: [50, 200, 250, 300, 375],
    employeesRequired: 30,
    desireBox: { baseDesirability: -6, stepDist: 1, stepVal: 1, maxRange: 6 },
    category: BuildingCategory.MILITARY,
  },
  CLAYPIT: {
    name: 'Clay Pit',
    height: 2,
    width: 2,
    cost: [8, 32, 40, 48, 60],
    employeesRequired: 8,
    desireBox: { baseDesirability: -3, stepDist: 1, stepVal: 1, maxRange: 2 },
    category: BuildingCategory.INDUSTRY,
  },
  CONSERVATORY: {
    name: 'Conservatory',
    height: 3,
    width: 3,
    cost: [20, 80, 100, 120, 150],
    employeesRequired: 8,
    desireBox: { baseDesirability: -3, stepDist: 1, stepVal: 1, maxRange: 3 },
    category: BuildingCategory.FUN,
  },
  COURTHOUSE: {
    name: 'Courthouse',
    height: 3,
    width: 3,
    cost: [30, 120, 150, 180, 225],
    employeesRequired: 10,
    desireBox: { baseDesirability: 8, stepDist: 2, stepVal: -2, maxRange: 3 },
    category: BuildingCategory.GOVT,
  },
  DANCESCHOOL: {
    name: 'Dance School',
    height: 4,
    width: 4,
    cost: [30, 120, 150, 180, 225],
    employeesRequired: 10,
    desireBox: { baseDesirability: -3, stepDist: 1, stepVal: 1, maxRange: 3 },
    category: BuildingCategory.FUN,
  },
  DENTIST: {
    name: 'Dentist',
    height: 1,
    width: 1,
    cost: [10, 40, 50, 60, 75],
    employeesRequired: 2,
    desireBox: { baseDesirability: 2, stepDist: 1, stepVal: -1, maxRange: 2 },
    category: BuildingCategory.HEALTH,
  },
  DOCK: {
    name: 'Dock',
    height: 3,
    width: 3,
    cost: [20, 80, 100, 120, 150],
    employeesRequired: 12,
    desireBox: { baseDesirability: -12, stepDist: 2, stepVal: 2, maxRange: 6 },
    category: BuildingCategory.STORAGE,
  },
  FERRYTERMINAL: {
    name: 'Ferry Terminal',
    height: 2,
    width: 2,
    cost: [8, 32, 40, 48, 60],
    employeesRequired: 5,
    desireBox: { baseDesirability: -5, stepDist: 2, stepVal: 2, maxRange: 4 },
    category: BuildingCategory.GOVT,
  },
  FESTIVALPAVILION: {
    name: 'Festival Pavilion',
    height: 5,
    width: 5,
    cost: [100, 400, 500, 600, 750],
    employeesRequired: 0,
    desireBox: { baseDesirability: 16, stepDist: 2, stepVal: -3, maxRange: 5 },
    category: BuildingCategory.RELIGION,
  },
  FIREHOUSE: {
    name: 'Firehouse',
    height: 1,
    width: 1,
    cost: [6, 24, 30, 36, 45],
    employeesRequired: 6,
    desireBox: { baseDesirability: -2, stepDist: 1, stepVal: 1, maxRange: 2 },
    category: BuildingCategory.GOVT,
  },
  FISHINGWHARF: {
    name: 'Fishing Wharf',
    height: 2,
    width: 2,
    cost: [12, 48, 60, 72, 90],
    employeesRequired: 6,
    desireBox: { baseDesirability: -8, stepDist: 2, stepVal: 2, maxRange: 4 },
    category: BuildingCategory.FOOD,
  },
  GARDEN: {
    name: 'Garden',
    height: 1,
    width: 1,
    cost: [3, 10, 12, 14, 18],
    employeesRequired: 0,
    desireBox: { baseDesirability: 3, stepDist: 1, stepVal: -1, maxRange: 3 },
    category: BuildingCategory.GOVT,
  },
  GATEHOUSE: {
    name: 'Gatehouse',
    height: 2,
    width: 5,
    cost: [80, 320, 400, 480, 600],
    employeesRequired: 0,
    desireBox: { baseDesirability: -4, stepDist: 1, stepVal: 1, maxRange: 4 },
    category: BuildingCategory.MILITARY,
  },
  GRANARY: {
    name: 'Granary',
    height: 4,
    width: 4,
    cost: [50, 200, 250, 300, 375],
    employeesRequired: 12,
    desireBox: { baseDesirability: -8, stepDist: 1, stepVal: 2, maxRange: 4 },
    category: BuildingCategory.STORAGE,
  },
  ARTISAN: {
    name: 'Guild, Artisans',
    height: 2,
    width: 2,
    cost: [30, 120, 150, 180, 225],
    employeesRequired: 20,
    desireBox: { baseDesirability: -6, stepDist: 1, stepVal: 1, maxRange: 4 },
    category: BuildingCategory.INDUSTRY,
  },
  BRICKLAYER: {
    name: 'Guild, Bricklayers',
    height: 2,
    width: 2,
    cost: [20, 80, 100, 120, 150],
    employeesRequired: 10,
    desireBox: { baseDesirability: -6, stepDist: 1, stepVal: 1, maxRange: 4 },
    category: BuildingCategory.INDUSTRY,
  },
  CARPENTER: {
    name: 'Guild, Carpenters',
    height: 2,
    width: 2,
    cost: [10, 40, 50, 60, 75],
    employeesRequired: 8,
    desireBox: { baseDesirability: -6, stepDist: 1, stepVal: 1, maxRange: 4 },
    category: BuildingCategory.INDUSTRY,
  },
  STONEMASON: {
    name: 'Guild, Stonemasons',
    height: 2,
    width: 2,
    cost: [30, 120, 150, 180, 225],
    employeesRequired: 12,
    desireBox: { baseDesirability: -6, stepDist: 1, stepVal: 1, maxRange: 4 },
    category: BuildingCategory.INDUSTRY,
  },
  HUNTINGLODGE: {
    name: 'Hunting Lodge',
    height: 2,
    width: 2,
    cost: [5, 20, 25, 30, 37],
    employeesRequired: 6,
    desireBox: { baseDesirability: -4, stepDist: 1, stepVal: 2, maxRange: 4 },
    category: BuildingCategory.FOOD,
  },
  JEWELER: {
    name: 'Jeweler',
    height: 2,
    width: 2,
    cost: [18, 75, 90, 110, 135],
    employeesRequired: 12,
    desireBox: { baseDesirability: -2, stepDist: 1, stepVal: 1, maxRange: 2 },
    category: BuildingCategory.INDUSTRY,
  },
  JUGGLERSCHOOL: {
    name: 'Juggler School',
    height: 2,
    width: 2,
    cost: [10, 40, 50, 60, 75],
    employeesRequired: 5,
    desireBox: { baseDesirability: 2, stepDist: 1, stepVal: -1, maxRange: 2 },
    category: BuildingCategory.FUN,
  },
  LAMPMAKER: {
    name: 'Lamp Maker',
    height: 2,
    width: 2,
    cost: [20, 80, 100, 120, 150],
    employeesRequired: 12,
    desireBox: { baseDesirability: -4, stepDist: 1, stepVal: 1, maxRange: 4 },
    category: BuildingCategory.INDUSTRY,
  },
  LIBRARY: {
    name: 'Library',
    height: 3,
    width: 3,
    cost: [90, 360, 450, 540, 675],
    employeesRequired: 30,
    desireBox: { baseDesirability: 8, stepDist: 2, stepVal: -2, maxRange: 6 },
    category: BuildingCategory.EDUCATION,
  },
  MANSIONSMALL: {
    name: 'Mansion, Personal',
    height: 3,
    width: 3,
    cost: [30, 120, 150, 180, 225],
    employeesRequired: 0,
    desireBox: { baseDesirability: 12, stepDist: 2, stepVal: -2, maxRange: 4 },
    category: BuildingCategory.GOVT,
  },
  MANSIONMEDIUM: {
    name: 'Mansion, Family',
    height: 4,
    width: 4,
    cost: [80, 320, 400, 480, 600],
    employeesRequired: 0,
    desireBox: { baseDesirability: 20, stepDist: 2, stepVal: -3, maxRange: 5 },
    category: BuildingCategory.GOVT,
  },
  MANSIONLARGE: {
    name: 'Mansion, Dynasty',
    height: 5,
    width: 5,
    cost: [140, 560, 700, 840, 1050],
    employeesRequired: 0,
    desireBox: { baseDesirability: 28, stepDist: 2, stepVal: -4, maxRange: 6 },
    category: BuildingCategory.GOVT,
  },
  COPPERMINE: {
    name: 'Mine, Copper',
    height: 2,
    width: 2,
    cost: [30, 120, 150, 180, 225],
    employeesRequired: 10,
    desireBox: { baseDesirability: -12, stepDist: 2, stepVal: 2, maxRange: 6 },
    category: BuildingCategory.INDUSTRY,
  },
  GEMSTONEMINE: {
    name: 'Mine, Gemstone',
    height: 2,
    width: 2,
    cost: [80, 320, 400, 480, 600],
    employeesRequired: 8,
    desireBox: { baseDesirability: -12, stepDist: 2, stepVal: 2, maxRange: 6 },
    category: BuildingCategory.INDUSTRY,
  },
  GOLDMINE: {
    name: 'Mine, Gold',
    height: 2,
    width: 2,
    cost: [50, 200, 250, 300, 375],
    employeesRequired: 12,
    desireBox: { baseDesirability: -16, stepDist: 2, stepVal: 3, maxRange: 6 },
    category: BuildingCategory.INDUSTRY,
  },
  MORTUARY: {
    name: 'Mortuary',
    height: 2,
    width: 2,
    cost: [20, 80, 100, 120, 150],
    employeesRequired: 8,
    desireBox: { baseDesirability: -3, stepDist: 2, stepVal: 1, maxRange: 2 },
    category: BuildingCategory.HEALTH,
  },
  PAINTMAKER: {
    name: 'Paint Maker',
    height: 2,
    width: 2,
    cost: [20, 80, 100, 120, 150],
    employeesRequired: 12,
    desireBox: { baseDesirability: -4, stepDist: 1, stepVal: 1, maxRange: 4 },
    category: BuildingCategory.INDUSTRY,
  },
  PALACESMALL: {
    name: 'Palace, Village',
    height: 4,
    width: 4,
    cost: [180, 720, 900, 1080, 1350],
    employeesRequired: 20,
    desireBox: { baseDesirability: 20, stepDist: 2, stepVal: -4, maxRange: 4 },
    category: BuildingCategory.GOVT,
  },
  PALACEMEDIUM: {
    name: 'Palace, Town',
    height: 5,
    width: 5,
    cost: [200, 800, 1000, 1200, 1500],
    employeesRequired: 25,
    desireBox: { baseDesirability: 22, stepDist: 2, stepVal: -5, maxRange: 5 },
    category: BuildingCategory.GOVT,
  },
  PALACEBIG: {
    name: 'Palace, City',
    height: 6,
    width: 6,
    cost: [240, 950, 1200, 1440, 1800],
    employeesRequired: 30,
    desireBox: { baseDesirability: 24, stepDist: 2, stepVal: -6, maxRange: 6 },
    category: BuildingCategory.GOVT,
  },
  PAPYRUSMAKER: {
    name: 'Papyrus Maker',
    height: 2,
    width: 2,
    cost: [20, 80, 100, 120, 150],
    employeesRequired: 12,
    desireBox: { baseDesirability: -4, stepDist: 1, stepVal: 1, maxRange: 4 },
    category: BuildingCategory.INDUSTRY,
  },
  PHYSICIAN: {
    name: 'Physician',
    height: 2,
    width: 2,
    cost: [10, 40, 50, 60, 75],
    employeesRequired: 8,
    desireBox: { baseDesirability: 2, stepDist: 1, stepVal: -1, maxRange: 2 },
    category: BuildingCategory.HEALTH,
  },
  PLAZA: {
    name: 'Plaza',
    height: 1,
    width: 1,
    cost: [3, 12, 15, 18, 22],
    employeesRequired: 0,
    desireBox: { baseDesirability: 4, stepDist: 1, stepVal: -2, maxRange: 2 },
    category: BuildingCategory.GOVT,
  },
  POLICESTATION: {
    name: 'Police Station',
    height: 1,
    width: 1,
    cost: [6, 24, 30, 36, 45],
    employeesRequired: 6,
    desireBox: { baseDesirability: -2, stepDist: 1, stepVal: 1, maxRange: 2 },
    category: BuildingCategory.GOVT,
  },
  POTTER: {
    name: 'Potter',
    height: 2,
    width: 2,
    cost: [12, 48, 60, 72, 90],
    employeesRequired: 12,
    desireBox: { baseDesirability: -4, stepDist: 1, stepVal: 1, maxRange: 4 },
    category: BuildingCategory.INDUSTRY,
  },
  GRANITE: {
    name: 'Quarry, Granite',
    height: 2,
    width: 2,
    cost: [20, 80, 100, 120, 150],
    employeesRequired: 12,
    desireBox: { baseDesirability: -6, stepDist: 1, stepVal: 1, maxRange: 6 },
    category: BuildingCategory.INDUSTRY,
  },
  LIMESTONE: {
    name: 'Quarry, Limestone',
    height: 2,
    width: 2,
    cost: [15, 60, 75, 90, 112],
    employeesRequired: 12,
    desireBox: { baseDesirability: -6, stepDist: 1, stepVal: 1, maxRange: 6 },
    category: BuildingCategory.INDUSTRY,
  },
  PLAINSTONE: {
    name: 'Quarry, Plain Stone',
    height: 2,
    width: 2,
    cost: [15, 60, 75, 90, 112],
    employeesRequired: 12,
    desireBox: { baseDesirability: -6, stepDist: 1, stepVal: 1, maxRange: 6 },
    category: BuildingCategory.INDUSTRY,
  },
  SANDSTONE: {
    name: 'Quarry, Sandstone',
    height: 2,
    width: 2,
    cost: [10, 40, 50, 60, 75],
    employeesRequired: 12,
    desireBox: { baseDesirability: -6, stepDist: 1, stepVal: 1, maxRange: 6 },
    category: BuildingCategory.INDUSTRY,
  },
  RECRUITER: {
    name: 'Recruiter',
    height: 3,
    width: 3,
    cost: [30, 120, 150, 180, 225],
    employeesRequired: 10,
    desireBox: { baseDesirability: -6, stepDist: 1, stepVal: 1, maxRange: 3 },
    category: BuildingCategory.MILITARY,
  },
  REEDGATHERER: {
    name: 'Reed Gatherer',
    height: 2,
    width: 2,
    cost: [10, 40, 50, 60, 75],
    employeesRequired: 8,
    desireBox: { baseDesirability: -2, stepDist: 1, stepVal: 1, maxRange: 2 },
    category: BuildingCategory.INDUSTRY,
  },
  ROAD: {
    name: 'Road',
    height: 1,
    width: 1,
    cost: [1, 3, 4, 5, 6],
    employeesRequired: 0,
    desireBox: { baseDesirability: 0, stepDist: 0, stepVal: 0, maxRange: 0 },
  },
  ROADBLOCK: {
    name: 'Roadblock',
    height: 1,
    width: 1,
    cost: [1, 4, 4, 5, 6],
    employeesRequired: 0,
    desireBox: { baseDesirability: 0, stepDist: 0, stepVal: 0, maxRange: 0 },
    category: BuildingCategory.GOVT,
  },
  SCRIBESCHOOL: {
    name: 'Scribe School',
    height: 2,
    width: 2,
    cost: [30, 120, 150, 180, 225],
    employeesRequired: 10,
    desireBox: { baseDesirability: 4, stepDist: 1, stepVal: -1, maxRange: 4 },
    category: BuildingCategory.EDUCATION,
  },
  SENETHOUSE: {
    name: 'Senet House',
    height: 4,
    width: 4,
    cost: [300, 1200, 1500, 1800, 2250],
    employeesRequired: 25,
    desireBox: { baseDesirability: -6, stepDist: 1, stepVal: 2, maxRange: 3 },
    category: BuildingCategory.FUN,
  },
  SHIPWRIGHT: {
    name: 'Shipwright',
    height: 3,
    width: 3,
    cost: [70, 280, 350, 420, 525],
    employeesRequired: 20,
    desireBox: { baseDesirability: -12, stepDist: 2, stepVal: 2, maxRange: 6 },
    category: BuildingCategory.INDUSTRY,
  },
  SHRINE: {
    name: 'Shrine',
    height: 1,
    width: 1,
    cost: [20, 80, 100, 120, 150],
    employeesRequired: 0,
    desireBox: { baseDesirability: 4, stepDist: 1, stepVal: -1, maxRange: 4 },
    category: BuildingCategory.RELIGION,
  },
  STATUESMALL: {
    name: 'Statue, Small',
    height: 1,
    width: 1,
    cost: [3, 10, 12, 14, 18],
    employeesRequired: 0,
    desireBox: { baseDesirability: 3, stepDist: 1, stepVal: -1, maxRange: 3 },
    category: BuildingCategory.GOVT,
  },
  STATUEMEDIUM: {
    name: 'Statue, Medium',
    height: 2,
    width: 2,
    cost: [12, 48, 60, 72, 90],
    employeesRequired: 0,
    desireBox: { baseDesirability: 10, stepDist: 1, stepVal: -2, maxRange: 4 },
    category: BuildingCategory.GOVT,
  },
  STATUELARGE: {
    name: 'Statue, Large',
    height: 3,
    width: 3,
    cost: [30, 120, 150, 180, 225],
    employeesRequired: 0,
    desireBox: { baseDesirability: 14, stepDist: 2, stepVal: -2, maxRange: 5 },
    category: BuildingCategory.GOVT,
  },
  TAXCOLLECTOR: {
    name: 'Tax Collector',
    height: 2,
    width: 2,
    cost: [15, 60, 75, 90, 112],
    employeesRequired: 6,
    desireBox: { baseDesirability: 3, stepDist: 1, stepVal: -1, maxRange: 3 },
    category: BuildingCategory.GOVT,
  },
  TEMPLE: {
    name: 'Temple',
    height: 3,
    width: 3,
    cost: [30, 120, 150, 180, 225],
    employeesRequired: 8,
    desireBox: { baseDesirability: 6, stepDist: 2, stepVal: -2, maxRange: 6 },
    category: BuildingCategory.RELIGION,
  },
  TOWER: {
    name: 'Tower',
    height: 2,
    width: 2,
    cost: [70, 270, 350, 420, 525],
    employeesRequired: 6,
    desireBox: { baseDesirability: -6, stepDist: 1, stepVal: 1, maxRange: 6 },
    category: BuildingCategory.MILITARY,
  },
  TRANSPORTWHARF: {
    name: 'Transport Wharf',
    height: 2,
    width: 2,
    cost: [40, 160, 200, 240, 300],
    employeesRequired: 5,
    desireBox: { baseDesirability: -2, stepDist: 1, stepVal: 1, maxRange: 2 },
    category: BuildingCategory.MILITARY,
  },
  WALL: {
    name: 'Wall',
    height: 1,
    width: 1,
    cost: [7, 28, 35, 42, 52],
    employeesRequired: 0,
    desireBox: { baseDesirability: 0, stepDist: 0, stepVal: 0, maxRange: 0 },
    category: BuildingCategory.MILITARY,
  },
  WARSHIPWHARF: {
    name: 'Warship Wharf',
    height: 3,
    width: 3,
    cost: [120, 480, 600, 720, 900],
    employeesRequired: 15,
    desireBox: { baseDesirability: -4, stepDist: 1, stepVal: 1, maxRange: 4 },
    category: BuildingCategory.MILITARY,
  },
  WATERLIFT: {
    name: 'Water Lift',
    height: 2,
    width: 2,
    cost: [6, 24, 30, 36, 45],
    employeesRequired: 5,
    desireBox: { baseDesirability: -3, stepDist: 1, stepVal: 1, maxRange: 3 },
    category: BuildingCategory.FOOD,
  },
  WATERSUPPLY: {
    name: 'Water Supply',
    height: 2,
    width: 2,
    cost: [10, 40, 50, 60, 75],
    employeesRequired: 5,
    desireBox: { baseDesirability: 4, stepDist: 1, stepVal: -1, maxRange: 4 },
    category: BuildingCategory.HEALTH,
  },
  WEAPONSMITH: {
    name: 'Weaponsmith',
    height: 2,
    width: 2,
    cost: [24, 100, 120, 145, 180],
    employeesRequired: 12,
    desireBox: { baseDesirability: -3, stepDist: 1, stepVal: 1, maxRange: 3 },
    category: BuildingCategory.MILITARY,
  },
  WEAVER: {
    name: 'Weaver',
    height: 2,
    width: 2,
    cost: [16, 64, 80, 96, 120],
    employeesRequired: 12,
    desireBox: { baseDesirability: -3, stepDist: 1, stepVal: 1, maxRange: 3 },
    category: BuildingCategory.INDUSTRY,
  },
  WELL: {
    name: 'Well',
    height: 1,
    width: 1,
    cost: [1, 4, 5, 6, 7],
    employeesRequired: 0,
    desireBox: { baseDesirability: 1, stepDist: 1, stepVal: -1, maxRange: 1 },
    category: BuildingCategory.HEALTH,
  },
  WOODCUTTER: {
    name: 'Wood Cutter',
    height: 2,
    width: 2,
    cost: [10, 40, 50, 60, 75],
    employeesRequired: 8,
    desireBox: { baseDesirability: -4, stepDist: 1, stepVal: 1, maxRange: 3 },
    category: BuildingCategory.INDUSTRY,
  },
  WORKCAMP: {
    name: 'Work Camp',
    height: 2,
    width: 2,
    cost: [12, 48, 60, 72, 90],
    employeesRequired: 20,
    desireBox: { baseDesirability: -3, stepDist: 1, stepVal: 1, maxRange: 3 },
    category: BuildingCategory.FOOD,
  },
  ZOO: {
    name: 'Zoo',
    height: 6,
    width: 6,
    cost: [500, 1500, 2000, 2200, 2600],
    employeesRequired: 30,
    desireBox: { baseDesirability: -6, stepDist: 1, stepVal: 2, maxRange: 3 },
    category: BuildingCategory.FUN,
  },
  STORAGEYARD: {
    name: 'Storage Yard',
    color: '#F5E2B4',
    height: 3,
    width: 3,
    cost: [14, 56, 70, 84, 105],
    employeesRequired: 6,
    //No desirebox of its own!
    children: [{ childKey: 'STORAGEYARD_HUT', relativeOrigin: { x: 0, y: 0 } }],
    category: BuildingCategory.STORAGE,
  },
  STORAGEYARD_HUT: {
    color: '#F8C1B5',
    height: 1,
    width: 1,
    desireBox: { baseDesirability: -5, stepDist: 2, stepVal: 2, maxRange: 3 },
  },
  TEMPLECOMPLEX: {
    name: 'Temple Complex',
    height: 7,
    width: 13,
    cost: [400, 1600, 2000, 2400, 3000],
    employeesRequired: 50,
    children: [
      { childKey: 'TC_ALTAR', relativeOrigin: { x: 4, y: 2 } },
      { childKey: 'TC_ALTAR', relativeOrigin: { x: 7, y: 2 } },
      { childKey: 'TC_ALTAR', relativeOrigin: { x: 10, y: 2 } },
    ],
    category: BuildingCategory.RELIGION,
  },
  TC_ALTAR: {
    height: 3,
    width: 3,
    desireBox: { baseDesirability: 20, stepDist: 2, stepVal: -4, maxRange: 6 },
  },
  FORT: {
    //I have no idea how the desirability for this one is calculated.
    name: 'Fort',
    height: 3,
    width: 3,
    cost: [200, 800, 1000, 1200, 1500],
    desireBox: { baseDesirability: -20, stepDist: 2, stepVal: 2, maxRange: 6 },
    children: [{ childKey: 'FORT_YARD', relativeOrigin: { x: 3, y: -1 } }],
    category: BuildingCategory.MILITARY,
  },
  FORT_YARD: {
    height: 4,
    width: 4,
    desireBox: { baseDesirability: -20, stepDist: 2, stepVal: 2, maxRange: 6 },
  },
} as const;

export function getBlueprint(
  key: keyof typeof BUILDING_BLUEPRINTS //keyof doesn't actually really DO anything if the record keys are of type string, go TS!
): BuildingBlueprint {
  if (!(key in BUILDING_BLUEPRINTS)) {
    throw new Error(`Could not find building of key: ${key}`);
  }
  return BUILDING_BLUEPRINTS[key];
}

export function getRandomBuildingBlueprint(): BuildingBlueprint {
  const allBlueprintKeys = Object.keys(BUILDING_BLUEPRINTS);

  const randomBlueprintKey =
    allBlueprintKeys[Math.floor(Math.random() * allBlueprintKeys.length)];
  return BUILDING_BLUEPRINTS[randomBlueprintKey];
}

/*
  BANDSTAND: {
      name: 'Bandstand',
      height: 3,
      width: 3,
      cost: [30, 130, 150, 180, 225],
      employeesRequired: 12,
      desireBoxes: [
        { baseDesirability: x, stepDist: x, stepVal: x, maxRange: x },
      ],
    },
  BOOTH: {
    name: 'Booth',
    height: 2,
    width: 2,
    cost: [10, 40, 50, 60, 75],
    employeesRequired: 8,
desireBox: { baseDesirability: x, stepDist: x, stepVal: x, maxRange: x }
  },
  PAVILION: {
    name: 'Pavilion',
    height: 4,
    width: 4,
    cost: [100, 400, 500, 600, 750],
    employeesRequired: 20,
desireBox: { baseDesirability: x, stepDist: x, stepVal: x, maxRange: x }
  },
  */
