import { DesireBox } from './DesireBox';
import { addPoints, Point, PointSet } from '../utils/geometry';
import { BUILDING_CATEGORIES } from './BuildingCategory';

export interface BuildingBlueprint {
  label?: string;
  fillColor?: string;
  borderColor?: string;
  width: number;
  height: number;
  cost?: number[]; //Array of 5 costs: v.easy, easy, normal, hard, v.hard
  employeesRequired?: number;
  desireBox?: DesireBox;
  children?: ChildBlueprint[];
  category?: keyof typeof BUILDING_CATEGORIES;
}

export interface ChildBlueprint {
  childKey: keyof typeof BUILDING_BLUEPRINTS;
  relativeOrigin: Point;
}

export function getBlueprint(
  key: keyof typeof BUILDING_BLUEPRINTS //keyof doesn't actually really DO anything if the record keys are of type string, go TS!
): BuildingBlueprint {
  if (!(key in BUILDING_BLUEPRINTS)) {
    throw new Error(`Could not find building of key: ${key}`);
  }
  return BUILDING_BLUEPRINTS[key];
}

export function getAllTiles(origin: Point, bp: BuildingBlueprint): PointSet {
  const tiles = new PointSet();
  for (let x = origin.x; x < origin.x + bp.width; x++) {
    for (let y = origin.y; y < origin.y + bp.height; y++) {
      const thisTile: Point = { x, y };
      tiles.add(thisTile);
    }
  }
  if (bp.children) {
    for (const child of bp.children) {
      const childBlueprint = getBlueprint(child.childKey);
      const childOrigin = addPoints(origin, child.relativeOrigin);
      for (const point of getAllTiles(childOrigin, childBlueprint)) {
        tiles.add(point);
      }
    }
  }
  return tiles;
}

export const BUILDING_BLUEPRINTS: Record<string, BuildingBlueprint> = {
  Academy: {
    label: 'Academy',
    height: 4,
    width: 4,
    cost: [200, 800, 1000, 1200, 1500],
    employeesRequired: 20,
    desireBox: { baseDesirability: -3, stepDist: 1, stepVal: 1, maxRange: 3 },
    category: 'MILITARY',
  },
  Apothecary: {
    label: 'Apothecary',
    height: 1,
    width: 1,
    cost: [6, 24, 30, 36, 45],
    employeesRequired: 5,
    desireBox: { baseDesirability: 1, stepDist: 1, stepVal: -1, maxRange: 1 },
    category: 'HEALTH',
  },
  Architect: {
    label: 'Architect',
    height: 1,
    width: 1,
    cost: [6, 24, 30, 36, 45],
    employeesRequired: 5,
    // No desirability effect!
    category: 'GOVT',
  },
  Bazaar: {
    label: 'Bazaar',
    height: 2,
    width: 2,
    cost: [8, 32, 40, 48, 60],
    employeesRequired: 5,
    desireBox: { baseDesirability: -2, stepDist: 1, stepVal: 1, maxRange: 6 },
    category: 'STORAGE',
  },
  Brewery: {
    label: 'Brewery',
    height: 2,
    width: 2,
    cost: [15, 60, 75, 90, 112],
    employeesRequired: 12,
    desireBox: { baseDesirability: -5, stepDist: 1, stepVal: 1, maxRange: 5 },
    category: 'INDUSTRY',
  },
  Brickworks: {
    label: 'Brickworks',
    height: 2,
    width: 2,
    cost: [12, 48, 60, 72, 90],
    employeesRequired: 12,
    desireBox: { baseDesirability: -4, stepDist: 1, stepVal: 1, maxRange: 4 },
    category: 'INDUSTRY',
  },
  'Cattle Ranch': {
    label: 'Cattle Ranch',
    height: 3,
    width: 3,
    cost: [15, 60, 75, 90, 112],
    employeesRequired: 12,
    desireBox: { baseDesirability: -4, stepDist: 1, stepVal: 1, maxRange: 4 },
    category: 'FOOD',
  },
  'Chariot Maker': {
    label: 'Chariot Maker',
    height: 4,
    width: 4,
    cost: [50, 200, 250, 300, 375],
    employeesRequired: 30,
    desireBox: { baseDesirability: -6, stepDist: 1, stepVal: 1, maxRange: 6 },
    category: 'MILITARY',
  },
  'Clay Pit': {
    label: 'Clay Pit',
    height: 2,
    width: 2,
    cost: [8, 32, 40, 48, 60],
    employeesRequired: 8,
    desireBox: { baseDesirability: -3, stepDist: 1, stepVal: 1, maxRange: 2 },
    category: 'INDUSTRY',
  },
  Conservatory: {
    label: 'Conservatory',
    height: 3,
    width: 3,
    cost: [20, 80, 100, 120, 150],
    employeesRequired: 8,
    desireBox: { baseDesirability: -3, stepDist: 1, stepVal: 1, maxRange: 3 },
    category: 'FUN',
  },
  Courthouse: {
    label: 'Courthouse',
    height: 3,
    width: 3,
    cost: [30, 120, 150, 180, 225],
    employeesRequired: 10,
    desireBox: { baseDesirability: 8, stepDist: 2, stepVal: -2, maxRange: 3 },
    category: 'GOVT',
  },
  'Dance School': {
    label: 'Dance School',
    height: 4,
    width: 4,
    cost: [30, 120, 150, 180, 225],
    employeesRequired: 10,
    desireBox: { baseDesirability: -3, stepDist: 1, stepVal: 1, maxRange: 3 },
    category: 'FUN',
  },
  Dentist: {
    label: 'Dentist',
    height: 1,
    width: 1,
    cost: [10, 40, 50, 60, 75],
    employeesRequired: 2,
    desireBox: { baseDesirability: 2, stepDist: 1, stepVal: -1, maxRange: 2 },
    category: 'HEALTH',
  },
  Dock: {
    label: 'Dock',
    height: 3,
    width: 3,
    cost: [20, 80, 100, 120, 150],
    employeesRequired: 12,
    desireBox: { baseDesirability: -12, stepDist: 2, stepVal: 2, maxRange: 6 },
    category: 'STORAGE',
  },
  'Ferry Terminal': {
    label: 'Ferry Terminal',
    height: 2,
    width: 2,
    cost: [8, 32, 40, 48, 60],
    employeesRequired: 5,
    desireBox: { baseDesirability: -5, stepDist: 2, stepVal: 2, maxRange: 4 },
    category: 'GOVT',
  },
  'Festival Pavilion': {
    label: 'Festival Pavilion',
    height: 5,
    width: 5,
    cost: [100, 400, 500, 600, 750],
    employeesRequired: 0,
    desireBox: { baseDesirability: 16, stepDist: 2, stepVal: -3, maxRange: 5 },
    category: 'RELIGION',
  },
  Firehouse: {
    label: 'Firehouse',
    height: 1,
    width: 1,
    cost: [6, 24, 30, 36, 45],
    employeesRequired: 6,
    desireBox: { baseDesirability: -2, stepDist: 1, stepVal: 1, maxRange: 2 },
    category: 'GOVT',
  },
  'Fishing Wharf': {
    label: 'Fishing Wharf',
    height: 2,
    width: 2,
    cost: [12, 48, 60, 72, 90],
    employeesRequired: 6,
    desireBox: { baseDesirability: -8, stepDist: 2, stepVal: 2, maxRange: 4 },
    category: 'FOOD',
  },
  Garden: {
    label: 'Garden',
    height: 1,
    width: 1,
    cost: [3, 10, 12, 14, 18],
    employeesRequired: 0,
    desireBox: { baseDesirability: 3, stepDist: 1, stepVal: -1, maxRange: 3 },
    category: 'GOVT',
  },
  Gatehouse: {
    label: 'Gatehouse',
    height: 2,
    width: 5,
    cost: [80, 320, 400, 480, 600],
    employeesRequired: 0,
    desireBox: { baseDesirability: -4, stepDist: 1, stepVal: 1, maxRange: 4 },
    category: 'MILITARY',
  },
  Granary: {
    label: 'Granary',
    height: 4,
    width: 4,
    cost: [50, 200, 250, 300, 375],
    employeesRequired: 12,
    desireBox: { baseDesirability: -8, stepDist: 1, stepVal: 2, maxRange: 4 },
    category: 'STORAGE',
  },
  'Guild, Artisans': {
    label: 'Artisan',
    height: 2,
    width: 2,
    cost: [30, 120, 150, 180, 225],
    employeesRequired: 20,
    desireBox: { baseDesirability: -6, stepDist: 1, stepVal: 1, maxRange: 4 },
    category: 'INDUSTRY',
  },
  'Guild, Bricklayers': {
    label: 'Bricklayer',
    height: 2,
    width: 2,
    cost: [20, 80, 100, 120, 150],
    employeesRequired: 10,
    desireBox: { baseDesirability: -6, stepDist: 1, stepVal: 1, maxRange: 4 },
    category: 'INDUSTRY',
  },
  'Guild, Carpenters': {
    label: 'Carpenter',
    height: 2,
    width: 2,
    cost: [10, 40, 50, 60, 75],
    employeesRequired: 8,
    desireBox: { baseDesirability: -6, stepDist: 1, stepVal: 1, maxRange: 4 },
    category: 'INDUSTRY',
  },
  'Guild, Stonemasons': {
    label: 'Stonemason',
    height: 2,
    width: 2,
    cost: [30, 120, 150, 180, 225],
    employeesRequired: 12,
    desireBox: { baseDesirability: -6, stepDist: 1, stepVal: 1, maxRange: 4 },
    category: 'INDUSTRY',
  },
  'Hunting Lodge': {
    label: 'Hunting Lodge',
    height: 2,
    width: 2,
    cost: [5, 20, 25, 30, 37],
    employeesRequired: 6,
    desireBox: { baseDesirability: -4, stepDist: 1, stepVal: 2, maxRange: 4 },
    category: 'FOOD',
  },
  Jeweler: {
    label: 'Jeweler',
    height: 2,
    width: 2,
    cost: [18, 75, 90, 110, 135],
    employeesRequired: 12,
    desireBox: { baseDesirability: -2, stepDist: 1, stepVal: 1, maxRange: 2 },
    category: 'INDUSTRY',
  },
  'Juggler School': {
    label: 'Juggler School',
    height: 2,
    width: 2,
    cost: [10, 40, 50, 60, 75],
    employeesRequired: 5,
    desireBox: { baseDesirability: 2, stepDist: 1, stepVal: -1, maxRange: 2 },
    category: 'FUN',
  },
  'Lamp Maker': {
    label: 'Lamp Maker',
    height: 2,
    width: 2,
    cost: [20, 80, 100, 120, 150],
    employeesRequired: 12,
    desireBox: { baseDesirability: -4, stepDist: 1, stepVal: 1, maxRange: 4 },
    category: 'INDUSTRY',
  },
  Library: {
    label: 'Library',
    height: 3,
    width: 3,
    cost: [90, 360, 450, 540, 675],
    employeesRequired: 30,
    desireBox: { baseDesirability: 8, stepDist: 2, stepVal: -2, maxRange: 6 },
    category: 'EDUCATION',
  },
  'Mansion, Personal': {
    label: 'Personal Mansion',
    height: 3,
    width: 3,
    cost: [30, 120, 150, 180, 225],
    employeesRequired: 0,
    desireBox: { baseDesirability: 12, stepDist: 2, stepVal: -2, maxRange: 4 },
    category: 'GOVT',
  },
  'Mansion, Family': {
    label: 'Family Mansion',
    height: 4,
    width: 4,
    cost: [80, 320, 400, 480, 600],
    employeesRequired: 0,
    desireBox: { baseDesirability: 20, stepDist: 2, stepVal: -3, maxRange: 5 },
    category: 'GOVT',
  },
  'Mansion, Dynasty': {
    label: 'Dynasty Mansion',
    height: 5,
    width: 5,
    cost: [140, 560, 700, 840, 1050],
    employeesRequired: 0,
    desireBox: { baseDesirability: 28, stepDist: 2, stepVal: -4, maxRange: 6 },
    category: 'GOVT',
  },
  'Mine, Copper': {
    label: 'Copper Mine',
    height: 2,
    width: 2,
    cost: [30, 120, 150, 180, 225],
    employeesRequired: 10,
    desireBox: { baseDesirability: -12, stepDist: 2, stepVal: 2, maxRange: 6 },
    category: 'INDUSTRY',
  },
  'Mine, Gemstone': {
    label: 'Gemstone Mine',
    height: 2,
    width: 2,
    cost: [80, 320, 400, 480, 600],
    employeesRequired: 8,
    desireBox: { baseDesirability: -12, stepDist: 2, stepVal: 2, maxRange: 6 },
    category: 'INDUSTRY',
  },
  'Mine, Gold': {
    label: 'Gold Mine',
    height: 2,
    width: 2,
    cost: [50, 200, 250, 300, 375],
    employeesRequired: 12,
    desireBox: { baseDesirability: -16, stepDist: 2, stepVal: 3, maxRange: 6 },
    category: 'INDUSTRY',
  },
  Mortuary: {
    label: 'Mortuary',
    height: 2,
    width: 2,
    cost: [20, 80, 100, 120, 150],
    employeesRequired: 8,
    desireBox: { baseDesirability: -3, stepDist: 2, stepVal: 1, maxRange: 2 },
    category: 'HEALTH',
  },
  'Paint Maker': {
    label: 'Paint Maker',
    height: 2,
    width: 2,
    cost: [20, 80, 100, 120, 150],
    employeesRequired: 12,
    desireBox: { baseDesirability: -4, stepDist: 1, stepVal: 1, maxRange: 4 },
    category: 'INDUSTRY',
  },
  'Palace, Village': {
    label: 'Palace, Village',
    height: 4,
    width: 4,
    cost: [180, 720, 900, 1080, 1350],
    employeesRequired: 20,
    desireBox: { baseDesirability: 20, stepDist: 2, stepVal: -4, maxRange: 4 },
    category: 'GOVT',
  },
  'Palace, Town': {
    label: 'Palace, Town',
    height: 5,
    width: 5,
    cost: [200, 800, 1000, 1200, 1500],
    employeesRequired: 25,
    desireBox: { baseDesirability: 22, stepDist: 2, stepVal: -5, maxRange: 5 },
    category: 'GOVT',
  },
  'Palace, City': {
    label: 'Palace, City',
    height: 6,
    width: 6,
    cost: [240, 950, 1200, 1440, 1800],
    employeesRequired: 30,
    desireBox: { baseDesirability: 24, stepDist: 2, stepVal: -6, maxRange: 6 },
    category: 'GOVT',
  },
  'Papyrus Maker': {
    label: 'Papyrus Maker',
    height: 2,
    width: 2,
    cost: [20, 80, 100, 120, 150],
    employeesRequired: 12,
    desireBox: { baseDesirability: -4, stepDist: 1, stepVal: 1, maxRange: 4 },
    category: 'INDUSTRY',
  },
  Physician: {
    label: 'Physician',
    height: 2,
    width: 2,
    cost: [10, 40, 50, 60, 75],
    employeesRequired: 8,
    desireBox: { baseDesirability: 2, stepDist: 1, stepVal: -1, maxRange: 2 },
    category: 'HEALTH',
  },
  Plaza: {
    label: 'Plaza',
    height: 1,
    width: 1,
    cost: [3, 12, 15, 18, 22],
    employeesRequired: 0,
    desireBox: { baseDesirability: 4, stepDist: 1, stepVal: -2, maxRange: 2 },
    category: 'GOVT',
  },
  'Police Station': {
    label: 'Police Station',
    height: 1,
    width: 1,
    cost: [6, 24, 30, 36, 45],
    employeesRequired: 6,
    desireBox: { baseDesirability: -2, stepDist: 1, stepVal: 1, maxRange: 2 },
    category: 'GOVT',
  },
  Potter: {
    label: 'Potter',
    height: 2,
    width: 2,
    cost: [12, 48, 60, 72, 90],
    employeesRequired: 12,
    desireBox: { baseDesirability: -4, stepDist: 1, stepVal: 1, maxRange: 4 },
    category: 'INDUSTRY',
  },
  'Quarry, Granite': {
    label: 'Quarry, Granite',
    height: 2,
    width: 2,
    cost: [20, 80, 100, 120, 150],
    employeesRequired: 12,
    desireBox: { baseDesirability: -6, stepDist: 1, stepVal: 1, maxRange: 6 },
    category: 'INDUSTRY',
  },
  'Quarry, Limestone': {
    label: 'Quarry, Limestone',
    height: 2,
    width: 2,
    cost: [15, 60, 75, 90, 112],
    employeesRequired: 12,
    desireBox: { baseDesirability: -6, stepDist: 1, stepVal: 1, maxRange: 6 },
    category: 'INDUSTRY',
  },
  'Quarry, Plain Stone': {
    label: 'Quarry, Plain Stone',
    height: 2,
    width: 2,
    cost: [15, 60, 75, 90, 112],
    employeesRequired: 12,
    desireBox: { baseDesirability: -6, stepDist: 1, stepVal: 1, maxRange: 6 },
    category: 'INDUSTRY',
  },
  'Quarry, Sandstone': {
    label: 'Quarry, Sandstone',
    height: 2,
    width: 2,
    cost: [10, 40, 50, 60, 75],
    employeesRequired: 12,
    desireBox: { baseDesirability: -6, stepDist: 1, stepVal: 1, maxRange: 6 },
    category: 'INDUSTRY',
  },
  Recruiter: {
    label: 'Recruiter',
    height: 3,
    width: 3,
    cost: [30, 120, 150, 180, 225],
    employeesRequired: 10,
    desireBox: { baseDesirability: -6, stepDist: 1, stepVal: 1, maxRange: 3 },
    category: 'MILITARY',
  },
  'Reed Gatherer': {
    label: 'Reed Gatherer',
    height: 2,
    width: 2,
    cost: [10, 40, 50, 60, 75],
    employeesRequired: 8,
    desireBox: { baseDesirability: -2, stepDist: 1, stepVal: 1, maxRange: 2 },
    category: 'INDUSTRY',
  },
  Road: {
    label: 'Road',
    height: 1,
    width: 1,
    cost: [1, 3, 4, 5, 6],
    employeesRequired: 0,
    desireBox: { baseDesirability: 0, stepDist: 0, stepVal: 0, maxRange: 0 },
  },
  Roadblock: {
    label: 'Roadblock',
    height: 1,
    width: 1,
    cost: [1, 4, 4, 5, 6],
    employeesRequired: 0,
    desireBox: { baseDesirability: 0, stepDist: 0, stepVal: 0, maxRange: 0 },
    category: 'GOVT',
  },
  'Scribe School': {
    label: 'Scribe School',
    height: 2,
    width: 2,
    cost: [30, 120, 150, 180, 225],
    employeesRequired: 10,
    desireBox: { baseDesirability: 4, stepDist: 1, stepVal: -1, maxRange: 4 },
    category: 'EDUCATION',
  },
  'Senet House': {
    label: 'Senet House',
    height: 4,
    width: 4,
    cost: [300, 1200, 1500, 1800, 2250],
    employeesRequired: 25,
    desireBox: { baseDesirability: -6, stepDist: 1, stepVal: 2, maxRange: 3 },
    category: 'FUN',
  },
  Shipwright: {
    label: 'Shipwright',
    height: 3,
    width: 3,
    cost: [70, 280, 350, 420, 525],
    employeesRequired: 20,
    desireBox: { baseDesirability: -12, stepDist: 2, stepVal: 2, maxRange: 6 },
    category: 'INDUSTRY',
  },
  Shrine: {
    label: 'Shrine',
    height: 1,
    width: 1,
    cost: [20, 80, 100, 120, 150],
    employeesRequired: 0,
    desireBox: { baseDesirability: 4, stepDist: 1, stepVal: -1, maxRange: 4 },
    category: 'RELIGION',
  },
  'Statue, Small': {
    label: 'Statue, Small',
    height: 1,
    width: 1,
    cost: [3, 10, 12, 14, 18],
    employeesRequired: 0,
    desireBox: { baseDesirability: 3, stepDist: 1, stepVal: -1, maxRange: 3 },
    category: 'GOVT',
  },
  'Statue, Medium': {
    label: 'Statue, Medium',
    height: 2,
    width: 2,
    cost: [12, 48, 60, 72, 90],
    employeesRequired: 0,
    desireBox: { baseDesirability: 10, stepDist: 1, stepVal: -2, maxRange: 4 },
    category: 'GOVT',
  },
  'Statue, Large': {
    label: 'Statue, Large',
    height: 3,
    width: 3,
    cost: [30, 120, 150, 180, 225],
    employeesRequired: 0,
    desireBox: { baseDesirability: 14, stepDist: 2, stepVal: -2, maxRange: 5 },
    category: 'GOVT',
  },
  'Tax Collector': {
    label: 'Tax Collector',
    height: 2,
    width: 2,
    cost: [15, 60, 75, 90, 112],
    employeesRequired: 6,
    desireBox: { baseDesirability: 3, stepDist: 1, stepVal: -1, maxRange: 3 },
    category: 'GOVT',
  },
  Temple: {
    label: 'Temple',
    height: 3,
    width: 3,
    cost: [30, 120, 150, 180, 225],
    employeesRequired: 8,
    desireBox: { baseDesirability: 6, stepDist: 2, stepVal: -2, maxRange: 6 },
    category: 'RELIGION',
  },
  Tower: {
    label: 'Tower',
    height: 2,
    width: 2,
    cost: [70, 270, 350, 420, 525],
    employeesRequired: 6,
    desireBox: { baseDesirability: -6, stepDist: 1, stepVal: 1, maxRange: 6 },
    category: 'MILITARY',
  },
  'Transport Wharf': {
    label: 'Transport Wharf',
    height: 2,
    width: 2,
    cost: [40, 160, 200, 240, 300],
    employeesRequired: 5,
    desireBox: { baseDesirability: -2, stepDist: 1, stepVal: 1, maxRange: 2 },
    category: 'MILITARY',
  },
  Wall: {
    label: 'Wall',
    height: 1,
    width: 1,
    cost: [7, 28, 35, 42, 52],
    employeesRequired: 0,
    desireBox: { baseDesirability: 0, stepDist: 0, stepVal: 0, maxRange: 0 },
    category: 'MILITARY',
  },
  'Warship Wharf': {
    label: 'Warship Wharf',
    height: 3,
    width: 3,
    cost: [120, 480, 600, 720, 900],
    employeesRequired: 15,
    desireBox: { baseDesirability: -4, stepDist: 1, stepVal: 1, maxRange: 4 },
    category: 'MILITARY',
  },
  'Water Lift': {
    label: 'Water Lift',
    height: 2,
    width: 2,
    cost: [6, 24, 30, 36, 45],
    employeesRequired: 5,
    desireBox: { baseDesirability: -3, stepDist: 1, stepVal: 1, maxRange: 3 },
    category: 'FOOD',
  },
  'Water Supply': {
    label: 'Water Supply',
    height: 2,
    width: 2,
    cost: [10, 40, 50, 60, 75],
    employeesRequired: 5,
    desireBox: { baseDesirability: 4, stepDist: 1, stepVal: -1, maxRange: 4 },
    category: 'HEALTH',
  },
  Weaponsmith: {
    label: 'Weaponsmith',
    height: 2,
    width: 2,
    cost: [24, 100, 120, 145, 180],
    employeesRequired: 12,
    desireBox: { baseDesirability: -3, stepDist: 1, stepVal: 1, maxRange: 3 },
    category: 'MILITARY',
  },
  Weaver: {
    label: 'Weaver',
    height: 2,
    width: 2,
    cost: [16, 64, 80, 96, 120],
    employeesRequired: 12,
    desireBox: { baseDesirability: -3, stepDist: 1, stepVal: 1, maxRange: 3 },
    category: 'INDUSTRY',
  },
  Well: {
    label: 'Well',
    height: 1,
    width: 1,
    cost: [1, 4, 5, 6, 7],
    employeesRequired: 0,
    desireBox: { baseDesirability: 1, stepDist: 1, stepVal: -1, maxRange: 1 },
    category: 'HEALTH',
  },
  'Wood Cutter': {
    label: 'Wood Cutter',
    height: 2,
    width: 2,
    cost: [10, 40, 50, 60, 75],
    employeesRequired: 8,
    desireBox: { baseDesirability: -4, stepDist: 1, stepVal: 1, maxRange: 3 },
    category: 'INDUSTRY',
  },
  'Work Camp': {
    label: 'Work Camp',
    height: 2,
    width: 2,
    cost: [12, 48, 60, 72, 90],
    employeesRequired: 20,
    desireBox: { baseDesirability: -3, stepDist: 1, stepVal: 1, maxRange: 3 },
    category: 'FOOD',
  },
  Zoo: {
    label: 'Zoo',
    height: 6,
    width: 6,
    cost: [500, 1500, 2000, 2200, 2600],
    employeesRequired: 30,
    desireBox: { baseDesirability: -6, stepDist: 1, stepVal: 2, maxRange: 3 },
    category: 'FUN',
  },
  'Storage Yard': {
    label: 'Storage Yard',
    fillColor: '#F5E2B4',
    height: 3,
    width: 3,
    cost: [14, 56, 70, 84, 105],
    employeesRequired: 6,
    //No desirebox of its own!
    children: [
      { childKey: 'Storage Yard Hut', relativeOrigin: { x: 0, y: 0 } },
    ],
    category: 'STORAGE',
  },
  'Storage Yard Hut': {
    fillColor: '#F8C1B5',
    height: 1,
    width: 1,
    desireBox: { baseDesirability: -5, stepDist: 2, stepVal: 2, maxRange: 3 },
  },
  'Temple Complex_1': {
    label: 'Temple Complex',
    height: 7,
    width: 13,
    cost: [400, 1600, 2000, 2400, 3000],
    employeesRequired: 50,
    children: [
      { childKey: 'Temple Complex Altar', relativeOrigin: { x: 0, y: 2 } },
      { childKey: 'Temple Complex Altar', relativeOrigin: { x: 3, y: 2 } },
      { childKey: 'Temple Complex Altar', relativeOrigin: { x: 6, y: 2 } },
    ],
    category: 'RELIGION',
  },
  'Temple Complex_2': {
    label: 'Temple Complex',
    height: 13,
    width: 7,
    cost: [400, 1600, 2000, 2400, 3000],
    employeesRequired: 50,
    children: [
      { childKey: 'Temple Complex Altar', relativeOrigin: { x: 2, y: 0 } },
      { childKey: 'Temple Complex Altar', relativeOrigin: { x: 2, y: 3 } },
      { childKey: 'Temple Complex Altar', relativeOrigin: { x: 2, y: 6 } },
    ],
    category: 'RELIGION',
  },
  'Temple Complex Altar': {
    height: 3,
    width: 3,
    desireBox: { baseDesirability: 20, stepDist: 2, stepVal: -4, maxRange: 6 },
  },
  Fort: {
    label: 'Fort',
    height: 3,
    width: 3,
    cost: [200, 800, 1000, 1200, 1500],
    desireBox: { baseDesirability: -20, stepDist: 2, stepVal: 2, maxRange: 6 },
    children: [{ childKey: 'Fort Yard', relativeOrigin: { x: 3, y: -1 } }],
    category: 'MILITARY',
  },
  'Fort Yard': {
    height: 4,
    width: 4,
    desireBox: { baseDesirability: -20, stepDist: 2, stepVal: 2, maxRange: 6 },
  },
} as const;

/*
'Bandstand': {
label: 'Bandstand',
      height: 3,
      width: 3,
      cost: [30, 130, 150, 180, 225],
      employeesRequired: 12,
      desireBoxes: [
        { baseDesirability: x, stepDist: x, stepVal: x, maxRange: x },
      ],
    },
'Booth': {
label: 'Booth',
    height: 2,
    width: 2,
    cost: [10, 40, 50, 60, 75],
    employeesRequired: 8,
desireBox: { baseDesirability: x, stepDist: x, stepVal: x, maxRange: x }
  },
'Pavilion': {
label: 'Pavilion',
    height: 4,
    width: 4,
    cost: [100, 400, 500, 600, 750],
    employeesRequired: 20,
desireBox: { baseDesirability: x, stepDist: x, stepVal: x, maxRange: x }
  },
  */
